
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Wise & Well Member',false,1,NULL,NULL,NULL,'metaReferral:001',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Keswick Representative',true,2,NULL,NULL,NULL,'metaReferral:002',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Family/Friend',true,3,NULL,NULL,NULL,'metaReferral:003',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Action in Maturity',false,4,NULL,NULL,NULL,'metaReferral:004',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Physician',true,5,NULL,NULL,NULL,'metaReferral:005',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Newspaper Ad',true,6,NULL,NULL,NULL,'metaReferral:006',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('TV Ad',true,7,NULL,NULL,NULL,'metaReferral:007',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Radio Ad',true,8,NULL,NULL,NULL,'metaReferral:008',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Keswick Website',false,9,NULL,NULL,NULL,'metaReferral:009',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Keswick FaceBook Page',false,10,NULL,NULL,NULL,'metaReferral:010',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_referral(value,description_required,value_order,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Other',true,11,NULL,NULL,NULL,'metaReferral:011',NULL,NULL,NULL,NULL,NULL,false);