
UPDATE meta_social_needs SET display_value = 'Educating / Coaching Client on Self-Advocacy' WHERE id = 'metaSocialNeeds:001';
UPDATE meta_social_needs SET value = '{"correspondenceWFederalAgency":"Correspondence with Federal Agency","CorrespondenceWLocalAgency":"Correspondence with Local Agency","CorrespondenceWStateAgency":"Correspondence with State Agency"}' WHERE id = 'metaSocialNeeds:002';
UPDATE meta_social_needs SET type = 'bool',value = '[]',is_multiple_allow = false,display_value = 'On Behalf of Client to Service Provider' WHERE id = 'metaSocialNeeds:003';
UPDATE meta_social_needs SET value = '{"adl":"ADL/Functional Assessment","individual":"Individual/Personal Assessment","intake":"Home Assessment","clientNeeds":"Client Needs Assessment"}' WHERE id = 'metaSocialNeeds:004';
UPDATE meta_social_needs SET value = '{"adl":"ADL Assessment","individual":"Individual Assessment","intake":"Home Assessment","clientNeeds":"Client Needs Assessment"}' WHERE id = 'metaSocialNeeds:005';
UPDATE meta_social_needs SET display_value = 'Veterans Administration' WHERE id = 'metaSocialNeeds:026';
UPDATE meta_social_needs SET display_value = 'Foreclosure Prevention' WHERE id = 'metaSocialNeeds:031';
UPDATE meta_social_needs SET display_value = 'Linked with Outside Conflict Resolution Provider' WHERE id = 'metaSocialNeeds:032';
UPDATE meta_social_needs SET display_value = 'Client – Client/Peer' WHERE id = 'metaSocialNeeds:035';
UPDATE meta_social_needs SET display_value = 'Elder Abuse/Neglect - Adult Protective Services / Other' WHERE id = 'metaSocialNeeds:038';
UPDATE meta_social_needs SET display_value = 'Intervention Requested by External Party' WHERE id = 'metaSocialNeeds:041';
UPDATE meta_social_needs SET display_value = 'Response to Critical Incident: Prevent Client Harm / Suicide' WHERE id = 'metaSocialNeeds:045';
UPDATE meta_social_needs SET type = 'bool',value = '[]' WHERE id = 'metaSocialNeeds:059';
UPDATE meta_social_needs SET display_value = 'Quality Time -Assured/Offered Support for Future Needs' WHERE id = 'metaSocialNeeds:062';
UPDATE meta_social_needs SET display_value = 'Consult with Hospital Discharge Planner' WHERE id = 'metaSocialNeeds:064';
UPDATE meta_social_needs SET status = 'inactive' WHERE id = 'metaSocialNeeds:085';
UPDATE meta_social_needs SET display_value = 'Telephone Access/Options' WHERE id = 'metaSocialNeeds:100';
UPDATE meta_social_needs SET display_value = 'Due to Apt Inspection Failure / Management Referral / Local Agency' WHERE id = 'metaSocialNeeds:104';
UPDATE meta_social_needs SET display_value = 'Private Pay Homemaker Supports' WHERE id = 'metaSocialNeeds:107';
UPDATE meta_social_needs SET display_value = 'Client-to-Client/Other Networking/Relationship Building' WHERE id = 'metaSocialNeeds:109';
UPDATE meta_social_needs SET display_value = 'Apartment Inspection Education/Support' WHERE id = 'metaSocialNeeds:112';
UPDATE meta_social_needs SET display_value = 'House Rules Violation Education/Support' WHERE id = 'metaSocialNeeds:114';
UPDATE meta_social_needs SET display_value = 'HUD/Housing Agency/Property Management Policy Clarification' WHERE id = 'metaSocialNeeds:115';
UPDATE meta_social_needs SET display_value = 'Recertification/Rental Application support' WHERE id = 'metaSocialNeeds:116';
UPDATE meta_social_needs SET value_order = '6' WHERE id = 'metaSocialNeeds:133';
UPDATE meta_social_needs SET value_order = '2' WHERE id = 'metaSocialNeeds:134';
UPDATE meta_social_needs SET value_order = '7' WHERE id = 'metaSocialNeeds:135';
UPDATE meta_social_needs SET value_order = '3' WHERE id = 'metaSocialNeeds:136';
UPDATE meta_social_needs SET value_order = '8' WHERE id = 'metaSocialNeeds:137';
UPDATE meta_social_needs SET value_order = '9' WHERE id = 'metaSocialNeeds:138';
UPDATE meta_social_needs SET value_order = '4' WHERE id = 'metaSocialNeeds:139';
UPDATE meta_social_needs SET value_order = '5' WHERE id = 'metaSocialNeeds:140';
UPDATE meta_social_needs SET display_value = 'Introduction to Service Coordinator/ Professional Services' WHERE id = 'metaSocialNeeds:146';
UPDATE meta_social_needs SET status = 'inactive' WHERE id = 'metaSocialNeeds:149';
UPDATE meta_social_needs SET value = '{"join":"Join","start":"Start/Engage"}' WHERE id = 'metaSocialNeeds:152';
UPDATE meta_social_needs SET display_value = 'Hosted Low or No-Cost Tax Services at Community Site' WHERE id = 'metaSocialNeeds:158';
UPDATE meta_social_needs SET display_value = 'Apartment complex/unit' WHERE id = 'metaSocialNeeds:163';
UPDATE meta_social_needs SET value_order = '7' WHERE id = 'metaSocialNeeds:168';
UPDATE meta_social_needs SET value_order = '8' WHERE id = 'metaSocialNeeds:169';
UPDATE meta_social_needs SET display_value = 'Transition Back to Home',value_order = '9' WHERE id = 'metaSocialNeeds:170';
UPDATE meta_social_needs SET display_value = 'Outing/Group Trip' WHERE id = 'metaSocialNeeds:176';
UPDATE meta_social_needs SET display_value = 'Vehicle / Personal Car Maintenance / Motor Vehicle Agency' WHERE id = 'metaSocialNeeds:185';
INSERT INTO meta_social_needs(key,type,value,is_multiple_allow,display_value,category_id,value_order,status,created_on_date,created_on_time,created_by,meta_social_needs_category_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('hospital','bool','[]',false,'Hospital',NULL,'6','active',NULL,NULL,NULL,'metaSocialNeedsCategory:023','metaSocialNeeds:187',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_social_needs(key,type,value,is_multiple_allow,display_value,category_id,value_order,status,created_on_date,created_on_time,created_by,meta_social_needs_category_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('adaFairHousingEducation','bool','[]',false,'ADA/Fair Housing Education',NULL,'1','active',NULL,NULL,NULL,'metaSocialNeedsCategory:026','metaSocialNeeds:188',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_social_needs(key,type,value,is_multiple_allow,display_value,category_id,value_order,status,created_on_date,created_on_time,created_by,meta_social_needs_category_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('assistedObtainingFairHousingCounsel','bool','[]',false,'Assisted with Obtaining Fair Housing Counsel',NULL,'2','active',NULL,NULL,NULL,'metaSocialNeedsCategory:026','metaSocialNeeds:189',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_social_needs(key,type,value,is_multiple_allow,display_value,category_id,value_order,status,created_on_date,created_on_time,created_by,meta_social_needs_category_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('voterRegistrationAssistance','bool','[]',false,'Voter Registration/Assistance',NULL,'3','active',NULL,NULL,NULL,'metaSocialNeedsCategory:026','metaSocialNeeds:190',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_social_needs(key,type,value,is_multiple_allow,display_value,category_id,value_order,status,created_on_date,created_on_time,created_by,meta_social_needs_category_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('otherSocialNeeds','string','[]',false,'Other Social Needs',NULL,'1','active',NULL,NULL,NULL,'metaSocialNeedsCategory:027','metaSocialNeeds:191',NULL,NULL,NULL,NULL,NULL,false);