
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Strongly agree','1',NULL,NULL,NULL,'metaQuestion:001','metaAnswer:001',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Agree','2',NULL,NULL,NULL,'metaQuestion:001','metaAnswer:002',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Neither agree nor disagree','3',NULL,NULL,NULL,'metaQuestion:001','metaAnswer:003',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Disagree','4',NULL,NULL,NULL,'metaQuestion:001','metaAnswer:004',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Strongly disagree','5',NULL,NULL,NULL,'metaQuestion:001','metaAnswer:005',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Strongly agree','1',NULL,NULL,NULL,'metaQuestion:002','metaAnswer:006',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Agree','2',NULL,NULL,NULL,'metaQuestion:002','metaAnswer:007',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Neither agree nor disagree','3',NULL,NULL,NULL,'metaQuestion:002','metaAnswer:008',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Disagree','4',NULL,NULL,NULL,'metaQuestion:002','metaAnswer:009',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Strongly disagree','5',NULL,NULL,NULL,'metaQuestion:002','metaAnswer:010',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Excellent','1',NULL,NULL,NULL,'metaQuestion:003','metaAnswer:011',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Very Good','2',NULL,NULL,NULL,'metaQuestion:003','metaAnswer:012',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Good','3',NULL,NULL,NULL,'metaQuestion:003','metaAnswer:013',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Fair','4',NULL,NULL,NULL,'metaQuestion:003','metaAnswer:014',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_answer(answer,sort_order,created_on_date,created_on_time,created_by,meta_question_id,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('Poor','5',NULL,NULL,NULL,'metaQuestion:003','metaAnswer:015',NULL,NULL,NULL,NULL,NULL,false);