
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','course','category','Category','refer','','{"object":"courseCategory"}','[]',false,'[]',false,'',true,false,false,true,false,'',false);
UPDATE oml_property SET data_attributes = '{"minimLength":"10","maximLength":"10","regex":"/^[0-9\\)(\\- ]+$/"}' WHERE object = 'patientEmploymentInfo' AND organization_id = '' AND property = 'telephoneNumber';
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','name','Name','string','','[]','[]',false,'[]',false,'',true,true,false,true,false,'',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','createdOnDate','Created On Date','string','[]','{"format":"date"}','[]',false,'[]',false,'',false,false,false,false,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','createdOnTime','Created On Time','string','[]','{"format":"time"}','[]',false,'[]',false,'',false,false,false,false,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','createdBy','Created By','refer','[]','{"object":"synapUser"}','[]',false,'[]',false,'',false,false,false,true,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','id','Id','string','[]','[]','[]',false,'[]',false,'',false,false,false,false,true,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','tags','Tags','arrays','[]','[]','[]',false,'[]',false,'',false,false,false,true,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','organizationId','Organization Id','refer','[]','{"object":"organization"}','[]',false,'[]',false,NULL,false,false,false,false,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','customProperty','custom Property','json','[]','[]','[]',false,'[]',false,'',false,false,false,false,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','checksum','Checksum','string','[]','[]','[]',false,'[]',false,'',false,false,false,false,false,'Auto added field from syncronizer',false);
INSERT INTO oml_property(organization_id,object,property,display_name,data_type,search_config,data_attributes,dependency,is_calculated,calculation_formula,allow_multiple_values,default_value,display_when_referred,required,property_permissions,allow_edit,unique_index,comments,is_deleted) values ('','courseCategory','objectPath','Object Path','string','[]','{"format":"ltree"}','[]',false,'[]',false,'',false,false,false,false,false,'Auto added field from syncronizer',false);