
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('AuditLogDetailQuery','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:002',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('AuditLogDistinctPatient','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:003',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('AuditLogQuery','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:004',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('ClientSocialNeeds','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:006',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('ObjectSchemaQuery','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:023',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('ReportQuery','metaAuthPolicy:denyInstructorPatient','SQC',NULL,NULL,NULL,'metaOmlScript:027',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('AuditLoggerUpdate','metaAuthPolicy:denyInstructorPatient','SUC',NULL,NULL,NULL,'metaOmlScript:033',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('courseReplicateIncChild','metaAuthPolicy:denyInstructorPatient','SUC',NULL,NULL,NULL,'metaOmlScript:039',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('dailyScheduleEmail','metaAuthPolicy:AllowOnlySystem','SUC',NULL,NULL,NULL,'metaOmlScript:041',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('GenerateReportQuery','metaAuthPolicy:denyInstructorPatient','SUC',NULL,NULL,NULL,'metaOmlScript:047',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('userUnlockResendEmail','metaAuthPolicy:denyInstructorPatient','SUC',NULL,NULL,NULL,'metaOmlScript:067',NULL,NULL,NULL,NULL,NULL,false);
INSERT INTO meta_oml_script(name,authorization_policy,script_type,created_on_date,created_on_time,created_by,id,tags,organization_id,custom_property,checksum,object_path,is_deleted) values ('viewClient','{}','SUC',NULL,NULL,NULL,'metaOmlScript:068',NULL,NULL,NULL,NULL,NULL,false);